### PR TITLE
Move the CPU metadata dumping under a new config read lock

### LINKED ISSUE #370: Spurious "Hash of CPU metadata has changed unexpectedly" on msr_validate change
While testing the changes currently in #369, but probably unrelated to them, I triggered the below on Rocky Linux 9.5 in a VM with 4 CPUs (as seen via our remote logging:

```
2025-04-04T00:36:18Z LKRG: STATE: Changing 'profile_validate' from 3 (Heavy) to 4 (Paranoid)
2025-04-04T00:36:26Z LKRG: STATE: Changing 'profile_validate' from 4 (Paranoid) to 2 (Balanced)
2025-04-04T00:36:26Z LKRG: ALERT: DETECT: CPU: Hash of CPU metadata has changed unexpectedly
2025-04-04T00:36:26Z LKRG: ALERT: DETECT: Kernel: 1 checksums changed unexpectedly
2025-04-04T00:36:26Z LKRG: ALERT: BLOCK: Kernel: 1 checksums changed unexpectedly
2025-04-04T00:36:26Z Kernel panic - not syncing: Kernel: 1 checksums changed unexpectedly
2025-04-04T00:36:26Z CPU: 0 PID: 1037682 Comm: kworker/u256:4 Kdump: loaded Tainted: G           OE     -------  ---  5.14.0-503.22.1.el9_5.x86_64 #1
2025-04-04T00:36:26Z Hardware name: oVirt RHEL/RHEL-AV, BIOS 1.16.0-4.module_el8+603+e0ca2c01 04/01/2014
2025-04-04T00:36:26Z Workqueue: events_unbound p_check_integrity [lkrg]
2025-04-04T00:36:26Z Call Trace:
2025-04-04T00:36:26Z  <TASK>
2025-04-04T00:36:26Z  dump_stack_lvl+0x34/0x48
2025-04-04T00:36:26Z  panic+0x107/0x2bb
2025-04-04T00:36:26Z  p_check_integrity.cold+0xa57/0xc49 [lkrg]
2025-04-04T00:36:26Z  ? srso_return_thunk+0x5/0x5f
2025-04-04T00:36:26Z  ? __schedule+0x231/0x550
2025-04-04T00:36:26Z  ? try_to_wake_up+0x69/0x530
2025-04-04T00:36:26Z  process_one_work+0x197/0x380
2025-04-04T00:36:26Z  worker_thread+0x2fe/0x410
2025-04-04T00:36:26Z  ? __pfx_worker_thread+0x10/0x10
2025-04-04T00:36:26Z  kthread+0xe0/0x100
2025-04-04T00:36:26Z  ? __pfx_kthread+0x10/0x10
2025-04-04T00:36:26Z  ret_from_fork+0x2c/0x50
2025-04-04T00:36:26Z  </TASK>
```

I was running `sysctl` commands manually, so it wasn't a stress-test. However, to reproduce this again, I had to run `sysctl` in a shell loop for quite a while until this happened:

```
2025-04-04T00:41:56Z LKRG: ALIVE: LKRG initialized successfully
2025-04-04T00:41:56Z OOM killer enabled.
2025-04-04T00:41:56Z Restarting tasks ... done.
2025-04-04T00:42:20Z LKRG: STATE: Changing 'profile_validate' from 3 (Heavy) to 2 (Balanced)
2025-04-04T00:42:28Z LKRG: STATE: Changing 'profile_validate' from 2 (Balanced) to 1 (Light)
2025-04-04T00:42:32Z LKRG: STATE: Changing 'profile_validate' from 1 (Light) to 0 (Disabled)
2025-04-04T00:42:47Z LKRG: STATE: Changing 'profile_validate' from 0 (Disabled) to 4 (Paranoid)
2025-04-04T00:42:53Z LKRG: STATE: Changing 'profile_validate' from 4 (Paranoid) to 3 (Heavy)
2025-04-04T00:42:58Z LKRG: STATE: Changing 'profile_validate' from 3 (Heavy) to 2 (Balanced)
2025-04-04T00:43:00Z LKRG: STATE: Changing 'profile_validate' from 2 (Balanced) to 1 (Light)
2025-04-04T00:43:02Z LKRG: STATE: Changing 'profile_validate' from 1 (Light) to 0 (Disabled)
2025-04-04T00:43:06Z LKRG: STATE: Changing 'profile_validate' from 0 (Disabled) to 4 (Paranoid)
2025-04-04T00:43:11Z LKRG: STATE: Changing 'profile_validate' from 4 (Paranoid) to 0 (Disabled)
2025-04-04T00:43:17Z LKRG: STATE: Changing 'profile_validate' from 0 (Disabled) to 4 (Paranoid)
2025-04-04T00:43:22Z LKRG: STATE: Changing 'profile_validate' from 4 (Paranoid) to 1 (Light)
2025-04-04T00:43:26Z LKRG: STATE: Changing 'profile_validate' from 1 (Light) to 4 (Paranoid)
2025-04-04T00:43:27Z LKRG: STATE: Changing 'profile_validate' from 4 (Paranoid) to 3 (Heavy)
2025-04-04T00:43:31Z LKRG: STATE: Changing 'profile_validate' from 3 (Heavy) to 4 (Paranoid)
2025-04-04T00:43:32Z LKRG: STATE: Changing 'profile_validate' from 4 (Paranoid) to 2 (Balanced)
2025-04-04T00:44:23Z LKRG: STATE: Changing 'profile_validate' from 2 (Balanced) to 4 (Paranoid)
2025-04-04T00:44:24Z LKRG: STATE: Changing 'profile_validate' from 4 (Paranoid) to 2 (Balanced)
2025-04-04T00:44:25Z LKRG: STATE: Changing 'profile_validate' from 2 (Balanced) to 4 (Paranoid)
2025-04-04T00:44:25Z LKRG: STATE: Changing 'profile_validate' from 4 (Paranoid) to 2 (Balanced)
2025-04-04T00:44:26Z LKRG: STATE: Changing 'profile_validate' from 2 (Balanced) to 4 (Paranoid)
2025-04-04T00:44:27Z LKRG: STATE: Changing 'profile_validate' from 4 (Paranoid) to 2 (Balanced)
2025-04-04T00:44:27Z LKRG: STATE: Changing 'profile_validate' from 2 (Balanced) to 4 (Paranoid)
2025-04-04T00:44:28Z LKRG: STATE: Changing 'profile_validate' from 4 (Paranoid) to 2 (Balanced)
2025-04-04T00:44:34Z LKRG: STATE: Changing 'profile_validate' from 2 (Balanced) to 3 (Heavy)
2025-04-04T00:44:35Z LKRG: STATE: Changing 'profile_validate' from 3 (Heavy) to 4 (Paranoid)
2025-04-04T00:44:36Z LKRG: STATE: Changing 'profile_validate' from 4 (Paranoid) to 2 (Balanced)
2025-04-04T00:44:38Z LKRG: STATE: Changing 'profile_validate' from 2 (Balanced) to 4 (Paranoid)
2025-04-04T00:44:40Z LKRG: STATE: Changing 'profile_validate' from 4 (Paranoid) to 2 (Balanced)
2025-04-04T00:45:03Z LKRG: STATE: Changing 'profile_validate' from 2 (Balanced) to 4 (Paranoid)
2025-04-04T00:45:03Z LKRG: STATE: Changing 'profile_validate' from 4 (Paranoid) to 2 (Balanced)
2025-04-04T00:45:03Z LKRG: STATE: Changing 'profile_validate' from 2 (Balanced) to 4 (Paranoid)
2025-04-04T00:45:03Z LKRG: STATE: Changing 'profile_validate' from 4 (Paranoid) to 2 (Balanced)
2025-04-04T00:45:03Z LKRG: STATE: Changing 'profile_validate' from 2 (Balanced) to 4 (Paranoid)
2025-04-04T00:45:03Z LKRG: STATE: Changing 'profile_validate' from 4 (Paranoid) to 2 (Balanced)
2025-04-04T00:45:03Z LKRG: STATE: Changing 'profile_validate' from 2 (Balanced) to 4 (Paranoid)
2025-04-04T00:45:03Z LKRG: STATE: Changing 'profile_validate' from 4 (Paranoid) to 2 (Balanced)
2025-04-04T00:45:03Z LKRG: STATE: Changing 'profile_validate' from 2 (Balanced) to 4 (Paranoid)
2025-04-04T00:45:03Z LKRG: STATE: Changing 'profile_validate' from 4 (Paranoid) to 2 (Balanced)
2025-04-04T00:45:03Z LKRG: STATE: Changing 'profile_validate' from 2 (Balanced) to 4 (Paranoid)
2025-04-04T00:45:03Z LKRG: STATE: Changing 'profile_validate' from 4 (Paranoid) to 2 (Balanced)
2025-04-04T00:45:03Z LKRG: STATE: Changing 'profile_validate' from 2 (Balanced) to 4 (Paranoid)
2025-04-04T00:45:04Z LKRG: STATE: Changing 'profile_validate' from 4 (Paranoid) to 2 (Balanced)
2025-04-04T00:45:04Z LKRG: STATE: Changing 'profile_validate' from 2 (Balanced) to 4 (Paranoid)
2025-04-04T00:45:04Z LKRG: STATE: Changing 'profile_validate' from 4 (Paranoid) to 2 (Balanced)
2025-04-04T00:45:04Z LKRG: STATE: Changing 'profile_validate' from 2 (Balanced) to 4 (Paranoid)
2025-04-04T00:45:04Z LKRG: STATE: Changing 'profile_validate' from 4 (Paranoid) to 2 (Balanced)
2025-04-04T00:45:04Z LKRG: STATE: Changing 'profile_validate' from 2 (Balanced) to 4 (Paranoid)
[... lots of lines omitted ...]
2025-04-04T01:16:00Z LKRG: STATE: Changing 'profile_validate' from 2 (Balanced) to 4 (Paranoid)
2025-04-04T01:16:08Z LKRG: STATE: Changing 'profile_validate' from 4 (Paranoid) to 2 (Balanced)
2025-04-04T01:16:09Z LKRG: STATE: Changing 'profile_validate' from 2 (Balanced) to 4 (Paranoid)
2025-04-04T01:16:17Z LKRG: STATE: Changing 'profile_validate' from 4 (Paranoid) to 2 (Balanced)
2025-04-04T01:16:18Z LKRG: STATE: Changing 'profile_validate' from 2 (Balanced) to 4 (Paranoid)
2025-04-04T01:16:26Z LKRG: STATE: Changing 'profile_validate' from 4 (Paranoid) to 2 (Balanced)
2025-04-04T01:16:27Z LKRG: STATE: Changing 'profile_validate' from 2 (Balanced) to 4 (Paranoid)
2025-04-04T01:16:35Z LKRG: STATE: Changing 'profile_validate' from 4 (Paranoid) to 2 (Balanced)
2025-04-04T01:16:36Z LKRG: STATE: Changing 'profile_validate' from 2 (Balanced) to 4 (Paranoid)
2025-04-04T01:16:44Z LKRG: STATE: Changing 'profile_validate' from 4 (Paranoid) to 2 (Balanced)
2025-04-04T01:16:45Z LKRG: STATE: Changing 'profile_validate' from 2 (Balanced) to 4 (Paranoid)
2025-04-04T01:16:53Z LKRG: STATE: Changing 'profile_validate' from 4 (Paranoid) to 2 (Balanced)
2025-04-04T01:16:54Z LKRG: STATE: Changing 'profile_validate' from 2 (Balanced) to 4 (Paranoid)
2025-04-04T01:17:02Z LKRG: STATE: Changing 'profile_validate' from 4 (Paranoid) to 2 (Balanced)
2025-04-04T01:17:03Z LKRG: STATE: Changing 'profile_validate' from 2 (Balanced) to 4 (Paranoid)
2025-04-04T01:17:11Z LKRG: STATE: Changing 'profile_validate' from 4 (Paranoid) to 2 (Balanced)
2025-04-04T01:17:12Z LKRG: STATE: Changing 'profile_validate' from 2 (Balanced) to 4 (Paranoid)
2025-04-04T01:17:12Z LKRG: ALERT: DETECT: CPU: Hash of CPU metadata has changed unexpectedly
2025-04-04T01:17:12Z LKRG: ALERT: DETECT: Kernel: 1 checksums changed unexpectedly
2025-04-04T01:17:12Z LKRG: ALERT: BLOCK: Kernel: 1 checksums changed unexpectedly
2025-04-04T01:17:12Z Kernel panic - not syncing: Kernel: 1 checksums changed unexpectedly
2025-04-04T01:17:12Z CPU: 2 PID: 2951 Comm: kworker/u256:0 Kdump: loaded Tainted: G           OE     -------  ---  5.14.0-503.22.1.el9_5.x86_64 #1
2025-04-04T01:17:12Z Hardware name: oVirt RHEL/RHEL-AV, BIOS 1.16.0-4.module_el8+603+e0ca2c01 04/01/2014
2025-04-04T01:17:12Z Workqueue: events_unbound p_check_integrity [lkrg]
2025-04-04T01:17:12Z Call Trace:
2025-04-04T01:17:12Z  <TASK>
2025-04-04T01:17:12Z  dump_stack_lvl+0x34/0x48
2025-04-04T01:17:12Z  panic+0x107/0x2bb
2025-04-04T01:17:12Z  p_check_integrity.cold+0xa57/0xc49 [lkrg]
2025-04-04T01:17:12Z  process_one_work+0x197/0x380
2025-04-04T01:17:12Z  worker_thread+0x2fe/0x410
```

Note that the first time this happened right after transition from 4 to 2, and the second from 2 to 4.

I have no luck (so far at least) reproducing this with transitions between 1 and 2 (running in a loop for many hours by now):

```
2025-04-05T01:18:00Z LKRG: STATE: Changing 'profile_validate' from 1 (Light) to 2 (Balanced)
2025-04-05T01:18:01Z LKRG: STATE: Changing 'profile_validate' from 2 (Balanced) to 1 (Light)
2025-04-05T01:18:02Z LKRG: STATE: Changing 'profile_validate' from 1 (Light) to 2 (Balanced)
2025-04-05T01:18:03Z LKRG: STATE: Changing 'profile_validate' from 2 (Balanced) to 1 (Light)
2025-04-05T01:18:04Z LKRG: STATE: Changing 'profile_validate' from 1 (Light) to 2 (Balanced)
2025-04-05T01:18:05Z LKRG: STATE: Changing 'profile_validate' from 2 (Balanced) to 1 (Light)
2025-04-05T01:18:06Z LKRG: STATE: Changing 'profile_validate' from 1 (Light) to 2 (Balanced)
2025-04-05T01:18:07Z LKRG: STATE: Changing 'profile_validate' from 2 (Balanced) to 1 (Light)
```

### PR DESCRIPTION
**Pull request by solardiz**
and acquire the lock for writing on lkrg.msr_validate changes, which affect whether MSRs are included in the computed hash value.

Fixes #370

### How Has This Been Tested?

I am testing with:

```shell
while :; do sysctl lkrg.msr_validate=1; sysctl lkrg.msr_validate=0; done
```

I also trigger some coredumps in a loop, as this was causing softlocks with my previous attempts at fixing this issue (when I tried acquiring `p_db_lock`).

### CODE REVIEW

**Comment by solardiz** [comment]
Also testing with:

```shell
while :; do sysctl lkrg.trigger=1; sysctl lkrg.msr_validate=0; sysctl lkrg.trigger=1; sysctl lkrg.msr_validate=1; done
```

**Comment by solardiz** [comment]
Ended up triggering a variation of #375 after a couple of minutes:

```
[2025-04-19 22:23:22] [ 1144.598167] LKRG: ALERT: DETECT: Task: Namespace escape: nsproxy pointer corruption for pid 66759, name sysctl
 [2025-04-19 22:23:22] [ 1144.598194] BUG: kernel NULL pointer dereference, address: 0000000000000008
```

Other bugs like this make it harder to confirm we have indeed reliably fixed this one bug.

**Comment by solardiz** [comment]
This passes my tests now.

I think some of the old uses of `p_db_lock` that this patch preserves are now unneeded (and some maybe never were), but they should not hurt (except for performance).

File: src/modules/integrity_timer/p_integrity_timer.c [hunk 1]
```diff
@@ -220,7 +222,22 @@ void p_check_integrity(struct work_struct *p_work) {
    /* Now we are safe to disable IRQs on current core */
```
Comment (Adam-pi3) [inline src/modules/integrity_timer/p_integrity_timer.c:222]: This comment should be just before `spin_lock_irqsave(&p_db_lock,p_db_flags);` - it looks like over the time it was shifted

File: src/modules/database/CPU.c [hunk 2]
```diff
@@ -168,6 +168,7 @@ int p_cpu_online_action(unsigned int p_cpu) {
 
    p_text_section_lock();
    spin_lock(&p_db_lock);
+   read_lock(&p_config_lock);
```
Comment (Adam-pi3) [inline src/modules/database/CPU.c:171]: Shouldn't it be write_lock? CPU metadata may (and will) change when new CPU is changing the state

File: src/modules/database/CPU.c [hunk 3]
```diff
@@ -200,6 +202,7 @@ int p_cpu_dead_action(unsigned int p_cpu) {
...
```
Comment (Adam-pi3) [inline src/modules/database/CPU.c:205]: Same here (write_lock)

File: src/modules/database/arch/x86/p_switch_idt/p_switch_idt.c [hunk 4]
```diff
@@ -38,6 +38,7 @@ static struct kretprobe p_switch_idt_kretprobe = {
 int p_switch_idt_entry(struct kretprobe_instance *p_ri, struct pt_regs *p_regs) {
 
    spin_lock(&p_db_lock);
+   read_lock(&p_config_lock);
```
Comment (Adam-pi3) [inline src/modules/database/arch/x86/p_switch_idt/p_switch_idt.c:41]: Same here (write_lock)

File: src/modules/kmod/p_kmod_notifier.c [hunk 5]
```diff
@@ -101,10 +101,12 @@ static int p_module_event_notifier(struct notifier_block *p_this, unsigned long
 //   if (p_tmp->state == MODULE_STATE_GOING) { <- Linux kernel bug - might not update state value :(
    if (p_event == MODULE_STATE_GOING) {
 
+      read_lock(&p_config_lock);
```
Comment (Adam-pi3) [inline src/modules/kmod/p_kmod_notifier.c:104]: Same here (modules can change MSR) - 'write_lock'

File: src/modules/kmod/p_kmod_notifier.c [hunk 6]
```diff
@@ -173,10 +175,12 @@ static int p_module_event_notifier(struct notifier_block *p_this, unsigned long
 //      if (p_tmp->state == MODULE_STATE_LIVE) { <- Linux kernel bug - might not update state value :(
       if (p_event == MODULE_STATE_LIVE) {
 
+         read_lock(&p_config_lock);
```
Comment (Adam-pi3) [inline src/modules/kmod/p_kmod_notifier.c:178]: Same here (modules can change MSR) - 'write_lock'

**Review by Adam-pi3 — COMMENTED** [review]
@solardiz I think locks are wrong

**Comment by Adam-pi3** [comment]
@solardiz can you not merge changes before the review?

**Comment by solardiz** [comment]
@Adam-pi3 Sorry I didn't wait for your review. I did request a review, but I felt it was optional given the testing I already performed and that this would be easy to revise later if we need to.

I think the locks are right: the meaning of the new config lock is that it reflects whether LKRG _configuration_ is being written to, which only happens in the sysctl interface. It is no problem that MSRs may change outside of this lock (or when it's only read-locked).

Also, if we were to `write_lock` it in those other places, we'd have the same problems I had seen with the db spinlock, namely that we either disable IRQs (and then it may be wrong to use `on_each_cpu`) or we risk deadlocks on preemption.

File: src/modules/integrity_timer/p_integrity_timer.c (hunk 1 above)
Comment (solardiz) [reply src/modules/integrity_timer/p_integrity_timer.c:222]: Yes, this comment originally was here (first LKRG commit in 2017):

```c
   on_each_cpu(p_dump_IDT_MSR_CRx,p_tmp_cpus,true);

   put_online_cpus();

   /*
    * OK, so now get the same information for currently locked core!
    */
//   p_dump_IDT_MSR_CRx(p_tmp_cpus); // no return value

   /* Now we are safe to disable IRQs on current core */
   spin_lock_irqsave(&p_db_lock,p_db_flags);

   p_tmp_hash = hash_from_CPU_data(p_tmp_cpus);
```

Arguably, it's still precisely at the place where it's safe to disable IRQs - but no longer at the place where we actually do that (not to mix acquisition/release of different locks in weird and risky ways). I don't mind moving it to right before the `spin_lock_irqsave` again, or just removing it.

**Comment by Adam-pi3** [comment]
> I think the locks are right: the meaning of the new config lock is that it reflects whether LKRG configuration is being written to, which only happens in the sysctl interface. It is no problem that MSRs may change outside of this lock (or when it's only read-locked).

Ah... make sense. Thanks!
